CREATE TABLE IF NOT EXISTS categories(
category_id BIGINT AUTO_INCREMENT PRIMARY KEY,
name VARCHAR(255) NOT NULL UNIQUE ,
req_name VARCHAR(255) NOT NULL UNIQUE ,
deleted BOOLEAN NOT NULL
);

CREATE TABLE IF NOT EXISTS banners(
banner_id BIGINT AUTO_INCREMENT PRIMARY KEY,
name VARCHAR(255) NOT NULL UNIQUE ,
content TEXT NOT NULL ,
deleted BOOLEAN NOT NULL ,
price DECIMAL(6,2) UNSIGNED NOT NULL ,
category_id BIGINT REFERENCES categories(category_id)
);

CREATE TABLE IF NOT EXISTS request(
request_id BIGINT AUTO_INCREMENT PRIMARY KEY ,
banner_id BIGINT REFERENCES banners(banner_id),
user_agent TEXT NOT NULL,
ip_address VARCHAR(255) NOT NULL,
date TIMESTAMP NOT NULL
);
